# Data Files
training_data_file: heart.csv
# test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: target

pipeline_name: heart_disease_model
pipeline_save_file: heart_disease__model_output_v

features:      # final features to be use
  - age
  - sex
  - cp 
  - trestbps
  - chol  
  - fbs   
  - restecg
  - thalach
  - exang
  - oldpeak
  - slope
  - ca
  - thal

thal_var: thal

thal_mappings:
  normal: 0
  fixedd: 1
  reversible: 2
 
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 150
max_depth: 5
max_features: 3
