name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check Disk Space
        run: df -h

      - name: Clean Up Docker Resources
        run: |
          docker system prune -af
          docker volume prune -f

      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/heart_disease-fastapi:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f heart_disease-fastapi-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 8001:8001 --name heart_disease-fastapi-container $DOCKER_USER/heart_disease-fastapi:latest

